### ISSUE TITLE
Additional slashes treated as separate path

### ISSUE THREAD

**Issue by rgbkrk** [deconst/mapping-service#31]
If `/blog/stuff/` exists, then `/blog/////stuff///` should point to the content as well, according to RFC 3986, section 3.3 on path:

```
path-abempty  = *( "/" segment )
```

Try it out on this issue page to see for yourself. Originally noted in https://github.com/////////deconst/deconst-docs/issues//////////////////////////////////71

**Comment by rgbkrk** [comment]
Apparently GitHub's URL regex doesn't catch that but the browser (and GitHub's webserver) handle that just fine. :wink:

**Comment by smashwilson** [comment]
This should actually be handled in presenter - everything should be normalized by the time it hits the mapping service. Moving the issue :point_right:
