### ISSUE TITLE
Run in "validate" mode

### ISSUE THREAD

**Issue by smashwilson** [deconst/mapping-service#7]
Rather than waiting until the mapping service is attempting to parse a map repository to discover errors, it would be much better to provide immediate feedback in the form of a *validation mode* that can easily be run from, for example, a Travis "build" on the map repository, to tell someone if their PR contains incorrect mappings.

The easiest way to do this would be to accept a `--validate` command-line argument, which, if provided, only attempts to call the parsing function on the current working directory. It should emit detailed error messages for any problems that it finds (I set this up a little with the `.suggestion` field on `ParseError`) and exit with a zero or nonzero status depending on the health of that state of the repo.

**Comment by jrperritt** [comment]
Implemented [here](https://github.com/deconst/layout-service/commit/4a04452e7bf0dd13e450f88683e5a0a0b47f82db) and [here](https://github.com/deconst/mapping-service/commit/613f09d06841be888f0d58259275ad2b7f9a7287)
